### ISSUE TITLE
Sync Tasmota states after reboots

### ISSUE THREAD

**Issue by oscarb** [oscarb/home-assistant-config#105]
```
automation:
  - id: Sync Tasmota states
    alias: Sync Tasmota states
    initial_state: true
    trigger:
      platform: homeassistant
      event: start
    action:
    # sync state for devices with default fulltopics
    - service: mqtt.publish
      data:
        topic: cmnd/tasmotas/state
        payload: ''
```

Source: 
https://tasmota.github.io/docs/Home-Assistant/#useful-automations
